# Generated by Django 5.2.13 on 2026-09-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_categoria_id_alter_inventario_id_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(related_name='pedidos', through='ventas.DetallePedido', to='catalogo.producto'),
        ),
    ]
