# Generated by Django 5.2.13 on 2026-09-09 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_categoria_id_alter_inventario_id_and_more'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('notificar_oferta', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='clientes.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorito_de', to='catalogo.producto')),
            ],
            options={
                'unique_together': {('cliente', 'producto')},
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='productos_favoritos',
            field=models.ManyToManyField(related_name='clientes_que_lo_favoritearon', through='clientes.Favorito', to='catalogo.producto'),
        ),
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20)),
                ('recibir_newsletter', models.BooleanField(default=True)),
                ('preferencias', models.TextField(blank=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='clientes.cliente')),
            ],
        ),
    ]
