# Generated by Django 5.2.13 on 2026-09-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_favorito_cliente_productos_favoritos_perfilcliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorito',
            options={'ordering': ['-prioridad', '-fecha_agregado']},
        ),
        migrations.AddField(
            model_name='favorito',
            name='descuento_puntos',
            field=models.PositiveIntegerField(default=0, help_text='Puntos a descontar del carrito'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('oferta', 'En Oferta')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='favorito',
            name='prioridad',
            field=models.PositiveIntegerField(default=1, help_text='Prioridad del favorito (1=más importante)'),
        ),
    ]
