# Generated by Django 5.2.13 on 2026-09-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_favorito_options_favorito_descuento_puntos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('oferta', 'En Oferta'), ('comprado', 'Comprado')], default='activo', max_length=20),
        ),
    ]
